name: Publish new version to npm

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
env:
  CI_RUN: true
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/prepare-runner
      - run: pnpm --filter nanotags build
      - run: cp README.md LICENSE.md packages/nanotags/
      - run: pnpm --filter nanotags publish --no-git-checks --provenance
